version: "2"
services:
  ngrok:
    image: wernight/ngrok
    ports:
    - "8081:8081"
    command:
    - /bin/sh
    - -c
    - |
      ngrok start --all
    volumes:
    - .:/home/ngrok/.ngrok2/
    depends_on:
    - simple-web
    - ssh-server
  simple-web:
    build: simple-web/
    ports:
    - "8080:8080"
  ssh-server:
    build: ssh-server/
    ports:
    - "2222:22"
