version: "2"
services:
  ngrok:
    image: wernight/ngrok
    ports:
    - "8081:8081"
    command:
    - /bin/sh
    - -c
    - |
      ngrok start --all
    volumes:
    - .:/home/ngrok/.ngrok2/
    depends_on:
    - simple-web
    - ssh-server
    - nginx
  simple-web:
    build: simple-web/
  ssh-server:
    build: ssh-server/
  nginx:
    image: nginx
    ports:
    - "8080:8080"
    volumes:
    - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro